### PR TITLE
Fix loader with non blocking models

### LINKED ISSUE #313: Regression, non-blocking model support and initial page of results not hiding infinityLoader
Hey, 

Found an issue with the latest version 1.1.2
Seems that if using a non blocking model hook + hideOnInfinity and there is only one page of results, never seems to hide the infinity loader. 

[Here is a commit](https://github.com/Duder-onomy/ember-infinity/commit/b88015b900b436441532ea3aca0ea164aca7ac24) I made on my fork to demonstrate the issue, had to hack in some extra param support to the mirage serializer.

If you pull that commit in, you will see that the infinityLoader never drops. 
image

Debugging this, it seems like the observer added [here](https://github.com/ember-infinity/ember-infinity/blob/master/addon/components/infinity-loader.js#L106) does not seem to observe through the promise proxy of the non-blocking model.

I thought about something like this:
```
didInsertElement() {
    this._super(...arguments);

    this._loadStatusDidChange();
    this.addObserver('infinityModelContent.reachedInfinity', this, this._loadStatusDidChange);
    this.addObserver('hideOnInfinity', this, this._loadStatusDidChange);

    // Wait for the infinity model THEN trigger the load status...
    get(this, 'infinityModelContent').then(() => this._loadStatusDidChange());

    let scrollableArea = get(this, 'scrollable');
    let infinityModel = get(this, 'infinityModelContent');
    if (infinityModel) {
      set(infinityModel, '_scrollable', scrollableArea);
    }
  },
```
That does not work ^.

Please let me know if there is anything I can do to help. 

If you know the cause and can pseudo code it to me I don't mind adding failing tests and PR'ing. Just a little confused on what is happening under le hood.

### PR DESCRIPTION
**Pull request by snewcomer**
@Duder-onomy Hey!  👋 When you have a moment, do you think you could try this out and lmk how it goes?

close #313

### CODE REVIEW

**Comment by Duder-onomy** [comment]
@snewcomer I tried it out real quick and the infinity-loader never dropped (even though infinity had been reached)
On infinity models with 1 page of results, the loader drops. 
But on more normal, many paged models, the infinity loader never dropped. 

I will dig into it more tomorrow and give you some deets where I think it is failing. (also I should triple doggy check that my yarn.lock is pulling in your pull request correct )

**Comment by snewcomer** [comment]
So what I am noticing is that for non blocking models, even though we properly set `reachedInfinity` in the service, it is not being propagated via the observer.  Still looking

**Comment by Duder-onomy** [comment]
Ok, I dug into this a little bit. 

I could never get it to work with observers. I am not sure how observers and promises work together.

However, I dug into some old backbone.js code to see how I did something similar. The only big difference was that I used events instead of observers. I replaced the observers with plain old [Ember.Object.Evented](https://emberjs.com/api/ember/release/classes/Evented) and I could get everything working how we want. 

My changes were: 
* Mix ember evented into the infinity model factory.
* The infinity service's `_notifyInfinityModelLoaded` will trigger 'infinityModelLoaded' on the infinity model. 
* The infinity-loader component listens for that event on the infinity model... and
BOOM Everything works. 

^ While doing this refactor, I noticed that the `infinityModelContent` that we set on the `infinity-loader` might not be useful, given that to access it we have to `.then` everywhere, we could just use the passed in `infinityModel`.

Giving the infinityModel the ability to send events might be decently useful.

I did not run the tests as I was just modifying it in the node_modules dir.

Anyhow, those are my findings. If that works for you I don't mind opening a PR this afternoon.

**Comment by snewcomer** [comment]
Go ahead! Would love to see your work!!

**Comment by snewcomer** [comment]
@Duder-onomy Great idea to use `Evented`, esp since this is not a simple data down actions up scenario.  Let me know if this now works for ya now.  Tests are g2g!

**Comment by Duder-onomy** [comment]
@snewcomer You nailed it. I pulled in 37dcb5c8ecb7db3c36de615582ce3e1eeb5ff029 and everything works.

**Pull request merged**
