### PR TITLE
Load previous pages

### PR DESCRIPTION
**Pull request by claire-lee**
Adds the ability to load previous pages. For example, if the starting page was 3, this allows you to create an infinity loader component that would load page 2, etc.

The purpose of this was to make the infinite scroll list more SEO-friendly ([reference](https://webmasters.googleblog.com/2014/02/infinite-scroll-search-friendly.html)) by allowing each individual page to be accessed by query parameters and allowing previous pages to be loaded if the user doesn't start on the first page.

### CODE REVIEW

**Comment by svparijs** [comment]
Any chance the tests will be fixed and merged soon?

**Comment by hhff** [comment]
hoping to get to it asap @svparijs !

**Comment by hhff** [comment]
@svparijs - tests are back passing :)

**Comment by john-griffin** [comment]
Anything I can do to help land this one?

**Comment by snewcomer** [comment]
@claire-lee any chance you might still be interested in getting this PR in?  Will need to rebase master and fix merge conflicts (`git rebase -i origin/master` && `git rebase --continue` after fix conflicts).  If not, I or @john-griffin can help.

**Comment by StefanFransen** [comment]
Is anyone still working on this? If not I would like to fix this.

**Comment by snewcomer** [comment]
@StefanFransen Yeah we would love that! However, a few things to note:

1.  the 1-0 [branch](https://github.com/hhff/ember-infinity/tree/1-0) is the way forward.  It has a lot of awesome fixes and improvements.  So any PR's should be pointing to this branch.

2.  This [PR](https://github.com/hhff/ember-infinity/pull/242) replaces the scroll event listeners with `ember-in-viewport`.  I hope to get this in sometime this month (awaiting upstream PR [review](https://github.com/DockYard/ember-in-viewport/pull/113) and merge).  As a result, the implementation of this feature may be quite simple.  Not exactly sure what it will look like at this point though.

What are you thoughts based on the above two points?  Would definitely like to prioritize this once the above two are resolved (which will most likely happen in the coming weeks).

**Comment by StefanFransen** [comment]
@snewcomer The new branch and your PR looks awesome! I think I should wait with fixing this until your PR is reviewed and merged.

**Comment by snewcomer** [comment]
@claire-lee This PR - #259 - took some things for your work here, so thank you.  I didn't want to ask for a full re-write given the amount that has changed under the hood since you submitted this PR, so forgive me 🙏 

@StefanFransen or @claire-lee  If you feel like trying out/reviewing, please feel free!

**Comment by snewcomer** [comment]
I believe this is enabled in the beta series with `loadPrevious=true` in the infinity-loader component!

https://github.com/ember-infinity/ember-infinity#infinity-loader

**Pull request closed without merging**
