### PR TITLE
Trig infinityModelUpdated event

### PR DESCRIPTION
**Pull request by sly7-7**

### CODE REVIEW

**Comment by sly7-7** [comment]
I also use [ember-cli-swiper](https://github.com/Ember-Swiper/ember-cli-swiper), and I needed it to update when new records arrive. The only way I found was to call its `forceUpdate` function on `infinityModelUpdated` event.

**Comment by snewcomer** [comment]
@sly7-7 I'm not seeing ember-infinity used in that addon.  Does this seem like it would be something specific to your codebase?  What version of ember-infinity are you on?  Something > 1.0?

**Comment by sly7-7** [comment]
I'm on `"ember-infinity": "^1.2.3"`. And yes it is specific to my code base. Actually I need a way to notify to either a component or a controller that the infinityModel has been updated. I thought it was what 'infinityModelUpdated' meant. As I saw it in the [doc](https://github.com/ember-infinity/ember-infinity#model-event-hooks), I thought the the call to trigger was just forgotten

**Comment by snewcomer** [comment]
@sly7-7 Yean you are right and I can definitely see where the confusion comes from.  That language needs to be updated. Aside from that, is it possible to do your trigger work here in your app code? ->

```
const ExtendedInfinityModel = InfinityModel.extend({
  infinityModelUpdated({ lastPageLoaded, totalPages, newObjects }) {
    ...do trigger stuff here...
  }
});
```

**Comment by sly7-7** [comment]
Unfortunately no 😞 , I can't find a way to notify the controller in this hook.

**Comment by hhff** [comment]
Sylvian, you should use a service to proxy events to the swiper - whether
you inject a special service through an extended infinity model, or just
“listen” to changes on the infinity service itself. A your controller can
listen to events on the service through ember evented or similar!

Hope it helps!

**Pull request closed without merging**
