### PR TITLE
Reverse scroll

### PR DESCRIPTION
**Pull request by williamweckl**
Methods to use scroll up instead of scroll down and unshift instead push.

Motivated by the common chat problem.

### CODE REVIEW

**Comment by danilovaz** [comment]
This PR will amazing feature :+1:

**Comment by sebastianhelbig** [comment]
Is there a reason this never got merged?

**Comment by snewcomer** [comment]
@sebastianhelbig I'll take a look this weekend and see if I can come up with a solution.

**Comment by snewcomer** [comment]
Further elaboration - since a lot of the internals have changed with the 1.0.0-alpha releases, I'll see what can be saved from this / or if this PR still works!

**Comment by snewcomer** [comment]
In my mind, I have a fix for this.  Will see if I can find time this weekend.

**Comment by snewcomer** [comment]
I believe this is enabled in the beta series with the `loadPrevious` flag!

https://github.com/ember-infinity/ember-infinity#infinity-loader

**Pull request closed without merging**
